### ISSUE TITLE
Fix hirelings inventory, rule is clear, sheet is false.

### ISSUE THREAD

**Issue by yar0d** [yar0d/mausritter-sheet#29]
![Screenshot_20210512-162340-418](https://user-images.githubusercontent.com/190219/118121434-ca73a980-b3f1-11eb-8d6e-8c05356e4289.png)

Add body to hirelings other than beetle.

**Comment by fmefford** [comment]
Hi, I just made a quick fix for this. There are now two paw slots, two body slots, and two inventory. It's an old issue but I can still send a PR if you'd like.
